"""empty message

Revision ID: 9d81c62c419a
Revises: 751dc90779eb
Create Date: 2023-05-12 17:53:09.178263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d81c62c419a'
down_revision = '751dc90779eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('galaxy_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'galaxy', ['galaxy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('galaxy_id')

    # ### end Alembic commands ###
